# Generated by Django 2.2.7 on 2019-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191202_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='sex',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen approaching human'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was indifferent to human'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was heard kukking'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was heard moaning'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was heard quaaing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen running from human'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen flagging tail'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen twitching tail'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen chasing another squirrel'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen foraging for food'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(default=False, help_text='Whether the squirrel was seen running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_ID',
            field=models.CharField(help_text='ID for each squirrel sighting', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
