# Generated by Django 2.2.7 on 2019-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191206_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other activities of the squirrel', max_length=200),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific location of the squirrel', max_length=200),
        ),
    ]
